# Generated by Django 3.2.20 on 2023-10-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20230808_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='box_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='refund_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
