# Generated by Django 3.2.20 on 2023-10-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20231004_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='refund_balance',
        ),
    ]
