# Generated by Django 3.2.20 on 2023-08-08 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20230808_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street_address2',
            new_name='street_address',
        ),
    ]
