# Generated by Django 3.2.20 on 2023-08-09 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_alter_product_is_favorited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_favorited',
            field=models.ManyToManyField(blank=True, related_name='my_favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
