# Generated by Django 3.2.20 on 2023-10-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_is_favorited'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_eligible_for_return',
            field=models.BooleanField(default=False, help_text='Check this box if the product is eligible for box return.'),
        ),
    ]
