# Generated by Django 3.2.20 on 2023-10-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_eligible_for_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='box_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the box price for this product for refund calculation.', max_digits=6, null=True),
        ),
    ]
