# Generated by Django 3.2.20 on 2023-10-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_box_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='box_price',
        ),
    ]
